---- WARNING: This schema is for context only and is not meant to be run.
---- Table order and constraints may not be valid for execution.

--CREATE TABLE public.ai_suggestions (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  game_id uuid,
--  move_id uuid,
--  suggested_move text,
--  confidence numeric,
--  created_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT ai_suggestions_pkey PRIMARY KEY (id),
--  CONSTRAINT ai_suggestions_move_id_fkey FOREIGN KEY (move_id) REFERENCES public.game_moves(id)
--);
--CREATE TABLE public.app_users (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  email text NOT NULL UNIQUE,
--  username text NOT NULL UNIQUE,
--  full_name text,
--  avatar_url text,
--  created_at timestamp without time zone DEFAULT now(),
--  updated_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT app_users_pkey PRIMARY KEY (id)
--);
--CREATE TABLE public.feedbacks (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  user_id uuid,
--  message text,
--  created_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT feedbacks_pkey PRIMARY KEY (id),
--  CONSTRAINT feedbacks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
--);
--CREATE TABLE public.game_moves (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  game_id uuid,
--  move_number integer,
--  player_color text CHECK (player_color = ANY (ARRAY['white'::text, 'black'::text])),
--  from_square text,
--  to_square text,
--  from_piece text,
--  to_piece text,
--  notation text,
--  results_in_check boolean,
--  fen_str text,
--  created_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT game_moves_pkey PRIMARY KEY (id)
--);
--CREATE TABLE public.game_types (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  code text NOT NULL UNIQUE,
--  name text NOT NULL,
--  description text,
--  created_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT game_types_pkey PRIMARY KEY (id)
--);
--CREATE TABLE public.games (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  player_id uuid,
--  status text DEFAULT 'waiting'::text CHECK (status = ANY (ARRAY['waiting'::text, 'in_progress'::text, 'finished'::text])),
--  result text CHECK (result = ANY (ARRAY['win'::text, 'lose'::text, 'draw'::text])),
--  fen_start text DEFAULT 'startpos'::text,
--  fen_current text,
--  total_moves integer DEFAULT 0,
--  started_at timestamp with time zone DEFAULT now(),
--  ended_at timestamp with time zone,
--  created_at timestamp with time zone DEFAULT now(),
--  game_type_id uuid,
--  puzzle_id uuid,
--  CONSTRAINT games_pkey PRIMARY KEY (id),
--  CONSTRAINT games_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.app_users(id),
--  CONSTRAINT games_game_type_id_fkey FOREIGN KEY (game_type_id) REFERENCES public.game_types(id),
--  CONSTRAINT games_puzzle_id_fkey FOREIGN KEY (puzzle_id) REFERENCES public.training_puzzles(id)
--);
--CREATE TABLE public.payment_history (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  user_id uuid,
--  transaction_id text UNIQUE,
--  amount numeric NOT NULL,
--  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text])),
--  created_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT payment_history_pkey PRIMARY KEY (id),
--  CONSTRAINT payment_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
--);
--CREATE TABLE public.robot_commands (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  game_id uuid,
--  command text NOT NULL,
--  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'executing'::text, 'done'::text, 'error'::text])),
--  sent_at timestamp without time zone DEFAULT now(),
--  executed_at timestamp without time zone,
--  robot_id uuid,
--  CONSTRAINT robot_commands_pkey PRIMARY KEY (id),
--  CONSTRAINT robot_commands_robot_id_fkey FOREIGN KEY (robot_id) REFERENCES public.robots(id)
--);
--CREATE TABLE public.robot_logs (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  command_id uuid,
--  log_message text,
--  created_at timestamp without time zone DEFAULT now(),
--  robot_id uuid,
--  CONSTRAINT robot_logs_pkey PRIMARY KEY (id),
--  CONSTRAINT robot_logs_command_id_fkey FOREIGN KEY (command_id) REFERENCES public.robot_commands(id),
--  CONSTRAINT robot_logs_robot_id_fkey FOREIGN KEY (robot_id) REFERENCES public.robots(id)
--);
--CREATE TABLE public.robots (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  robot_code text NOT NULL UNIQUE,
--  name text,
--  location text,
--  is_online boolean DEFAULT false,
--  last_online_at timestamp without time zone,
--  move_speed_ms integer DEFAULT 1000,
--  created_at timestamp without time zone DEFAULT now(),
--  updated_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT robots_pkey PRIMARY KEY (id)
--);
--CREATE TABLE public.saved_states (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  game_id uuid,
--  player_id uuid,
--  fen_str text NOT NULL,
--  last_move_id uuid,
--  saved_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT saved_states_pkey PRIMARY KEY (id),
--  CONSTRAINT saved_states_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.app_users(id),
--  CONSTRAINT saved_states_last_move_id_fkey FOREIGN KEY (last_move_id) REFERENCES public.game_moves(id)
--);
--CREATE TABLE public.training_puzzles (
--  id uuid NOT NULL DEFAULT gen_random_uuid(),
--  fen_str text NOT NULL,
--  solution_move text NOT NULL,
--  difficulty text DEFAULT 'medium'::text CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])),
--  created_at timestamp without time zone DEFAULT now(),
--  CONSTRAINT training_puzzles_pkey PRIMARY KEY (id)
--);